//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerAziendale.SRDBAgendaAziendale {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRDBAgendaAziendale.IServiceDBAgendaAziendale")]
    public interface IServiceDBAgendaAziendale {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/TestConnessione", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/TestConnessioneResponse")]
        void TestConnessione();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/TestConnessione", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/TestConnessioneResponse")]
        System.Threading.Tasks.Task TestConnessioneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/Login", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/Login", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetInfoLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetInfoLavoratoreResponse")]
        string GetInfoLavoratore(string username, string username_cercato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetInfoLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetInfoLavoratoreResponse")]
        System.Threading.Tasks.Task<string> GetInfoLavoratoreAsync(string username, string username_cercato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/InserisciLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/InserisciLavoratoreResponse")]
        bool InserisciLavoratore(string username, string username_in, string password, string nome, string cognome, string residenza, string dataNascita, string email, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/InserisciLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/InserisciLavoratoreResponse")]
        System.Threading.Tasks.Task<bool> InserisciLavoratoreAsync(string username, string username_in, string password, string nome, string cognome, string residenza, string dataNascita, string email, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaLavoratoreResponse")]
        bool AggiornaLavoratore(string username, string username_in, string nome, string cognome, string residenza, string dataNascita, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaLavoratoreResponse")]
        System.Threading.Tasks.Task<bool> AggiornaLavoratoreAsync(string username, string username_in, string nome, string cognome, string residenza, string dataNascita, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/EliminaLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/EliminaLavoratoreResponse")]
        bool EliminaLavoratore(string username, string username_in);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/EliminaLavoratore", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/EliminaLavoratoreResponse")]
        System.Threading.Tasks.Task<bool> EliminaLavoratoreAsync(string username, string username_in);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoLavoratori", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoLavoratoriResponse")]
        string GetElencoLavoratori(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoLavoratori", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoLavoratoriResponse")]
        System.Threading.Tasks.Task<string> GetElencoLavoratoriAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/CreaEvento", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/CreaEventoResponse")]
        bool CreaEvento(string username, string nome, string descrizione, string dataInizio, string dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/CreaEvento", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/CreaEventoResponse")]
        System.Threading.Tasks.Task<bool> CreaEventoAsync(string username, string nome, string descrizione, string dataInizio, string dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaEvento", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaEventoResponse")]
        bool AggiornaEvento(string username, string codice, string id, string nome, string descrizione, string dataInizio, string dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaEvento", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/AggiornaEventoResponse")]
        System.Threading.Tasks.Task<bool> AggiornaEventoAsync(string username, string codice, string id, string nome, string descrizione, string dataInizio, string dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/EliminaEvento", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/EliminaEventoResponse")]
        bool EliminaEvento(string username, string codice, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/EliminaEvento", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/EliminaEventoResponse")]
        System.Threading.Tasks.Task<bool> EliminaEventoAsync(string username, string codice, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoEventi", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoEventiResponse")]
        string GetElencoEventi(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoEventi", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoEventiResponse")]
        System.Threading.Tasks.Task<string> GetElencoEventiAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/CreaProgetto", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/CreaProgettoResponse")]
        bool CreaProgetto(string username, string nome, string descrizione, string dataInizio, string dataFine, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/CreaProgetto", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/CreaProgettoResponse")]
        System.Threading.Tasks.Task<bool> CreaProgettoAsync(string username, string nome, string descrizione, string dataInizio, string dataFine, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoPartecipantiAttivita", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoPartecipantiAttivitaRespons" +
            "e")]
        string GetElencoPartecipantiAttivita(string username, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoPartecipantiAttivita", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/GetElencoPartecipantiAttivitaRespons" +
            "e")]
        System.Threading.Tasks.Task<string> GetElencoPartecipantiAttivitaAsync(string username, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/AggiungiPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/AggiungiPartecipanteAttivitaResponse" +
            "")]
        bool AggiungiPartecipanteAttivita(string username, string username_in, string codice, string ruolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/AggiungiPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/AggiungiPartecipanteAttivitaResponse" +
            "")]
        System.Threading.Tasks.Task<bool> AggiungiPartecipanteAttivitaAsync(string username, string username_in, string codice, string ruolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/RimuoviPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/RimuoviPartecipanteAttivitaResponse")]
        bool RimuoviPartecipanteAttivita(string username, string username_in, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDBAgendaAziendale/RimuoviPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceDBAgendaAziendale/RimuoviPartecipanteAttivitaResponse")]
        System.Threading.Tasks.Task<bool> RimuoviPartecipanteAttivitaAsync(string username, string username_in, string codice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDBAgendaAziendaleChannel : ServerAziendale.SRDBAgendaAziendale.IServiceDBAgendaAziendale, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDBAgendaAziendaleClient : System.ServiceModel.ClientBase<ServerAziendale.SRDBAgendaAziendale.IServiceDBAgendaAziendale>, ServerAziendale.SRDBAgendaAziendale.IServiceDBAgendaAziendale {
        
        public ServiceDBAgendaAziendaleClient() {
        }
        
        public ServiceDBAgendaAziendaleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDBAgendaAziendaleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBAgendaAziendaleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBAgendaAziendaleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TestConnessione() {
            base.Channel.TestConnessione();
        }
        
        public System.Threading.Tasks.Task TestConnessioneAsync() {
            return base.Channel.TestConnessioneAsync();
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string GetInfoLavoratore(string username, string username_cercato) {
            return base.Channel.GetInfoLavoratore(username, username_cercato);
        }
        
        public System.Threading.Tasks.Task<string> GetInfoLavoratoreAsync(string username, string username_cercato) {
            return base.Channel.GetInfoLavoratoreAsync(username, username_cercato);
        }
        
        public bool InserisciLavoratore(string username, string username_in, string password, string nome, string cognome, string residenza, string dataNascita, string email, string categoria) {
            return base.Channel.InserisciLavoratore(username, username_in, password, nome, cognome, residenza, dataNascita, email, categoria);
        }
        
        public System.Threading.Tasks.Task<bool> InserisciLavoratoreAsync(string username, string username_in, string password, string nome, string cognome, string residenza, string dataNascita, string email, string categoria) {
            return base.Channel.InserisciLavoratoreAsync(username, username_in, password, nome, cognome, residenza, dataNascita, email, categoria);
        }
        
        public bool AggiornaLavoratore(string username, string username_in, string nome, string cognome, string residenza, string dataNascita, string categoria) {
            return base.Channel.AggiornaLavoratore(username, username_in, nome, cognome, residenza, dataNascita, categoria);
        }
        
        public System.Threading.Tasks.Task<bool> AggiornaLavoratoreAsync(string username, string username_in, string nome, string cognome, string residenza, string dataNascita, string categoria) {
            return base.Channel.AggiornaLavoratoreAsync(username, username_in, nome, cognome, residenza, dataNascita, categoria);
        }
        
        public bool EliminaLavoratore(string username, string username_in) {
            return base.Channel.EliminaLavoratore(username, username_in);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaLavoratoreAsync(string username, string username_in) {
            return base.Channel.EliminaLavoratoreAsync(username, username_in);
        }
        
        public string GetElencoLavoratori(string username) {
            return base.Channel.GetElencoLavoratori(username);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoLavoratoriAsync(string username) {
            return base.Channel.GetElencoLavoratoriAsync(username);
        }
        
        public bool CreaEvento(string username, string nome, string descrizione, string dataInizio, string dataFine, string luogo) {
            return base.Channel.CreaEvento(username, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public System.Threading.Tasks.Task<bool> CreaEventoAsync(string username, string nome, string descrizione, string dataInizio, string dataFine, string luogo) {
            return base.Channel.CreaEventoAsync(username, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public bool AggiornaEvento(string username, string codice, string id, string nome, string descrizione, string dataInizio, string dataFine, string luogo) {
            return base.Channel.AggiornaEvento(username, codice, id, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public System.Threading.Tasks.Task<bool> AggiornaEventoAsync(string username, string codice, string id, string nome, string descrizione, string dataInizio, string dataFine, string luogo) {
            return base.Channel.AggiornaEventoAsync(username, codice, id, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public bool EliminaEvento(string username, string codice, string id) {
            return base.Channel.EliminaEvento(username, codice, id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaEventoAsync(string username, string codice, string id) {
            return base.Channel.EliminaEventoAsync(username, codice, id);
        }
        
        public string GetElencoEventi(string username) {
            return base.Channel.GetElencoEventi(username);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoEventiAsync(string username) {
            return base.Channel.GetElencoEventiAsync(username);
        }
        
        public bool CreaProgetto(string username, string nome, string descrizione, string dataInizio, string dataFine, string cliente) {
            return base.Channel.CreaProgetto(username, nome, descrizione, dataInizio, dataFine, cliente);
        }
        
        public System.Threading.Tasks.Task<bool> CreaProgettoAsync(string username, string nome, string descrizione, string dataInizio, string dataFine, string cliente) {
            return base.Channel.CreaProgettoAsync(username, nome, descrizione, dataInizio, dataFine, cliente);
        }
        
        public string GetElencoPartecipantiAttivita(string username, string codice) {
            return base.Channel.GetElencoPartecipantiAttivita(username, codice);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoPartecipantiAttivitaAsync(string username, string codice) {
            return base.Channel.GetElencoPartecipantiAttivitaAsync(username, codice);
        }
        
        public bool AggiungiPartecipanteAttivita(string username, string username_in, string codice, string ruolo) {
            return base.Channel.AggiungiPartecipanteAttivita(username, username_in, codice, ruolo);
        }
        
        public System.Threading.Tasks.Task<bool> AggiungiPartecipanteAttivitaAsync(string username, string username_in, string codice, string ruolo) {
            return base.Channel.AggiungiPartecipanteAttivitaAsync(username, username_in, codice, ruolo);
        }
        
        public bool RimuoviPartecipanteAttivita(string username, string username_in, string codice) {
            return base.Channel.RimuoviPartecipanteAttivita(username, username_in, codice);
        }
        
        public System.Threading.Tasks.Task<bool> RimuoviPartecipanteAttivitaAsync(string username, string username_in, string codice) {
            return base.Channel.RimuoviPartecipanteAttivitaAsync(username, username_in, codice);
        }
    }
}
