//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaAziendale.SRAgendaAziendale {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRAgendaAziendale.IServiceAgendaAziendale")]
    public interface IServiceAgendaAziendale {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/TestConnessione", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/TestConnessioneResponse")]
        void TestConnessione();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/TestConnessione", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/TestConnessioneResponse")]
        System.Threading.Tasks.Task TestConnessioneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/Login", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/Login", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetInfoLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetInfoLavoratoreResponse")]
        string GetInfoLavoratore(string username, string username_cercato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetInfoLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetInfoLavoratoreResponse")]
        System.Threading.Tasks.Task<string> GetInfoLavoratoreAsync(string username, string username_cercato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/InserisciLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/InserisciLavoratoreResponse")]
        bool InserisciLavoratore(string username, string username_in, string password, string nome, string cognome, string residenza, System.DateTime dataNascita, string email, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/InserisciLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/InserisciLavoratoreResponse")]
        System.Threading.Tasks.Task<bool> InserisciLavoratoreAsync(string username, string username_in, string password, string nome, string cognome, string residenza, System.DateTime dataNascita, string email, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/AggiornaLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/AggiornaLavoratoreResponse")]
        bool AggiornaLavoratore(string username, string username_in, string nome, string cognome, string residenza, System.DateTime dataNascita, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/AggiornaLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/AggiornaLavoratoreResponse")]
        System.Threading.Tasks.Task<bool> AggiornaLavoratoreAsync(string username, string username_in, string nome, string cognome, string residenza, System.DateTime dataNascita, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/EliminaLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/EliminaLavoratoreResponse")]
        bool EliminaLavoratore(string username, string username_in);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/EliminaLavoratore", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/EliminaLavoratoreResponse")]
        System.Threading.Tasks.Task<bool> EliminaLavoratoreAsync(string username, string username_in);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratori", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratoriResponse")]
        string GetElencoLavoratori(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratori", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratoriResponse")]
        System.Threading.Tasks.Task<string> GetElencoLavoratoriAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/CreaEvento", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/CreaEventoResponse")]
        bool CreaEvento(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/CreaEvento", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/CreaEventoResponse")]
        System.Threading.Tasks.Task<bool> CreaEventoAsync(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/AggiornaEvento", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/AggiornaEventoResponse")]
        bool AggiornaEvento(string username, string codice, string id, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/AggiornaEvento", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/AggiornaEventoResponse")]
        System.Threading.Tasks.Task<bool> AggiornaEventoAsync(string username, string codice, string id, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/EliminaEvento", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/EliminaEventoResponse")]
        bool EliminaEvento(string username, string codice, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/EliminaEvento", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/EliminaEventoResponse")]
        System.Threading.Tasks.Task<bool> EliminaEventoAsync(string username, string codice, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoEventi", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoEventiResponse")]
        string GetElencoEventi(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoEventi", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoEventiResponse")]
        System.Threading.Tasks.Task<string> GetElencoEventiAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/CreaProgetto", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/CreaProgettoResponse")]
        bool CreaProgetto(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/CreaProgetto", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/CreaProgettoResponse")]
        System.Threading.Tasks.Task<bool> CreaProgettoAsync(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoPartecipantiAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoPartecipantiAttivitaResponse")]
        string GetElencoPartecipantiAttivita(string username, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoPartecipantiAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoPartecipantiAttivitaResponse")]
        System.Threading.Tasks.Task<string> GetElencoPartecipantiAttivitaAsync(string username, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratoriAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratoriAttivitaResponse")]
        string GetElencoLavoratoriAttivita(string username, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratoriAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/GetElencoLavoratoriAttivitaResponse")]
        System.Threading.Tasks.Task<string> GetElencoLavoratoriAttivitaAsync(string username, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/AggiungiPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/AggiungiPartecipanteAttivitaResponse")]
        bool AggiungiPartecipanteAttivita(string username, string username_in, string codice, string ruolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/AggiungiPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/AggiungiPartecipanteAttivitaResponse")]
        System.Threading.Tasks.Task<bool> AggiungiPartecipanteAttivitaAsync(string username, string username_in, string codice, string ruolo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/RimuoviPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/RimuoviPartecipanteAttivitaResponse")]
        bool RimuoviPartecipanteAttivita(string username, string username_in, string codice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAgendaAziendale/RimuoviPartecipanteAttivita", ReplyAction="http://tempuri.org/IServiceAgendaAziendale/RimuoviPartecipanteAttivitaResponse")]
        System.Threading.Tasks.Task<bool> RimuoviPartecipanteAttivitaAsync(string username, string username_in, string codice);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAgendaAziendaleChannel : AgendaAziendale.SRAgendaAziendale.IServiceAgendaAziendale, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAgendaAziendaleClient : System.ServiceModel.ClientBase<AgendaAziendale.SRAgendaAziendale.IServiceAgendaAziendale>, AgendaAziendale.SRAgendaAziendale.IServiceAgendaAziendale {
        
        public ServiceAgendaAziendaleClient() {
        }
        
        public ServiceAgendaAziendaleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAgendaAziendaleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgendaAziendaleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAgendaAziendaleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TestConnessione() {
            base.Channel.TestConnessione();
        }
        
        public System.Threading.Tasks.Task TestConnessioneAsync() {
            return base.Channel.TestConnessioneAsync();
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public string GetInfoLavoratore(string username, string username_cercato) {
            return base.Channel.GetInfoLavoratore(username, username_cercato);
        }
        
        public System.Threading.Tasks.Task<string> GetInfoLavoratoreAsync(string username, string username_cercato) {
            return base.Channel.GetInfoLavoratoreAsync(username, username_cercato);
        }
        
        public bool InserisciLavoratore(string username, string username_in, string password, string nome, string cognome, string residenza, System.DateTime dataNascita, string email, string categoria) {
            return base.Channel.InserisciLavoratore(username, username_in, password, nome, cognome, residenza, dataNascita, email, categoria);
        }
        
        public System.Threading.Tasks.Task<bool> InserisciLavoratoreAsync(string username, string username_in, string password, string nome, string cognome, string residenza, System.DateTime dataNascita, string email, string categoria) {
            return base.Channel.InserisciLavoratoreAsync(username, username_in, password, nome, cognome, residenza, dataNascita, email, categoria);
        }
        
        public bool AggiornaLavoratore(string username, string username_in, string nome, string cognome, string residenza, System.DateTime dataNascita, string categoria) {
            return base.Channel.AggiornaLavoratore(username, username_in, nome, cognome, residenza, dataNascita, categoria);
        }
        
        public System.Threading.Tasks.Task<bool> AggiornaLavoratoreAsync(string username, string username_in, string nome, string cognome, string residenza, System.DateTime dataNascita, string categoria) {
            return base.Channel.AggiornaLavoratoreAsync(username, username_in, nome, cognome, residenza, dataNascita, categoria);
        }
        
        public bool EliminaLavoratore(string username, string username_in) {
            return base.Channel.EliminaLavoratore(username, username_in);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaLavoratoreAsync(string username, string username_in) {
            return base.Channel.EliminaLavoratoreAsync(username, username_in);
        }
        
        public string GetElencoLavoratori(string username) {
            return base.Channel.GetElencoLavoratori(username);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoLavoratoriAsync(string username) {
            return base.Channel.GetElencoLavoratoriAsync(username);
        }
        
        public bool CreaEvento(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo) {
            return base.Channel.CreaEvento(username, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public System.Threading.Tasks.Task<bool> CreaEventoAsync(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo) {
            return base.Channel.CreaEventoAsync(username, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public bool AggiornaEvento(string username, string codice, string id, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo) {
            return base.Channel.AggiornaEvento(username, codice, id, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public System.Threading.Tasks.Task<bool> AggiornaEventoAsync(string username, string codice, string id, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string luogo) {
            return base.Channel.AggiornaEventoAsync(username, codice, id, nome, descrizione, dataInizio, dataFine, luogo);
        }
        
        public bool EliminaEvento(string username, string codice, string id) {
            return base.Channel.EliminaEvento(username, codice, id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminaEventoAsync(string username, string codice, string id) {
            return base.Channel.EliminaEventoAsync(username, codice, id);
        }
        
        public string GetElencoEventi(string username) {
            return base.Channel.GetElencoEventi(username);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoEventiAsync(string username) {
            return base.Channel.GetElencoEventiAsync(username);
        }
        
        public bool CreaProgetto(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string cliente) {
            return base.Channel.CreaProgetto(username, nome, descrizione, dataInizio, dataFine, cliente);
        }
        
        public System.Threading.Tasks.Task<bool> CreaProgettoAsync(string username, string nome, string descrizione, System.DateTime dataInizio, System.DateTime dataFine, string cliente) {
            return base.Channel.CreaProgettoAsync(username, nome, descrizione, dataInizio, dataFine, cliente);
        }
        
        public string GetElencoPartecipantiAttivita(string username, string codice) {
            return base.Channel.GetElencoPartecipantiAttivita(username, codice);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoPartecipantiAttivitaAsync(string username, string codice) {
            return base.Channel.GetElencoPartecipantiAttivitaAsync(username, codice);
        }
        
        public string GetElencoLavoratoriAttivita(string username, string codice) {
            return base.Channel.GetElencoLavoratoriAttivita(username, codice);
        }
        
        public System.Threading.Tasks.Task<string> GetElencoLavoratoriAttivitaAsync(string username, string codice) {
            return base.Channel.GetElencoLavoratoriAttivitaAsync(username, codice);
        }
        
        public bool AggiungiPartecipanteAttivita(string username, string username_in, string codice, string ruolo) {
            return base.Channel.AggiungiPartecipanteAttivita(username, username_in, codice, ruolo);
        }
        
        public System.Threading.Tasks.Task<bool> AggiungiPartecipanteAttivitaAsync(string username, string username_in, string codice, string ruolo) {
            return base.Channel.AggiungiPartecipanteAttivitaAsync(username, username_in, codice, ruolo);
        }
        
        public bool RimuoviPartecipanteAttivita(string username, string username_in, string codice) {
            return base.Channel.RimuoviPartecipanteAttivita(username, username_in, codice);
        }
        
        public System.Threading.Tasks.Task<bool> RimuoviPartecipanteAttivitaAsync(string username, string username_in, string codice) {
            return base.Channel.RimuoviPartecipanteAttivitaAsync(username, username_in, codice);
        }
    }
}
